#!/usr/bin/env bash
#
# zandbak
#
# Run php sandbox shell commands
#
# Usage:
#   zandbak [--option <argument>]
#
# Options:
#   -h --help         Display this help information.
#   -b --base-path    Set base path.
#   -r --repos        Select repositories.
#   --debug           Display debug information.
#
# https://github.com/bramkok/zandbak

### Configuration
#####################################################################

set -eu -o pipefail
# shellcheck disable=SC2034
DEFAULT_IFS="${IFS}"
SAFER_IFS=$'\n\t'
IFS="${SAFER_IFS}"
_ME=$(basename "${0}") # Program basename


### Global variables
#####################################################################

# Default repository path
_BASE_PATH="/home/vagrant/repositories/"

# Repositories to run commands in
_REPOSITORIES=()

### Debug/Exit/Help
#####################################################################

__DEBUG_COUNTER=0
_debug() {
  if [[ "${_USE_DEBUG:-"0"}" -eq 1 ]]; then
    __DEBUG_COUNTER=$((__DEBUG_COUNTER+1))
    printf "%s " "${__DEBUG_COUNTER}"
    "${@}"
    printf "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――\n"
  fi
}

debug() {
  _debug echo "${@}"
}

_die() {
  "${@}" 1>&2
  exit 1
}

die() {
  _die echo "${@}"
}

_print_help() {
  cat <<HEREDOC

zandbak

Run php sandbox shell commands

Usage:
  ${_ME} [--option <argument>]

Options:
   -h --help         Display this help information.
   -b --base-path    Set base path.
   -r --repos        Select repositories.
   --debug           Display debug information.

HEREDOC
}

### Options
#####################################################################

# Short options followed by a ':' require an argument
optstring=xo:h

unset options
while ((${#})) # While the number of arguments is greater than 0
do
  case ${1} in
    -[!-]?*) # Option type: -ab
      for ((i=1; i<${#1}; i++))
      do
        c=${1:i:1} # Extract 1 character from position 'i'
        options+=("-${c}") # Add current char to options
        # If the option requires an argument, and it's not the last char
        # make the rest of the string its argument
        if [[ ${optstring} = *"${c}:"* && ${1:i+1} ]]; then
          options+=("${1:i+1}")
          break
        fi
      done
      ;;
    --?*=*) # Option type: --foo=bar, split on first '='
      options+=("${1%%=*}" "${1#*=}")
      ;;
    --) # End of options
      options+=(--endopts)
      shift
      options+=("${@}")
      break
      ;;
    *) # Else, nothing special
      options+=("${1}")
      ;;
  esac
  shift
done

set -- "${options[@]:-}"
unset options

# Option variables
_PRINT_HELP=0
_USE_DEBUG=0

_require_argument() {
  local _option="${1:-}"
  local _argument="${2:-}"
  if [[ -z "${_argument}" ]] || [[ "${_argument}" =~ ^- ]]; then
    _die printf "Option requires a argument: %s\n" "${_option}"
  fi
}

while [ ${#} -gt 0 ]
do
  __option="${1:-}"
  __maybe_param="${2:-}"
  case "${__option}" in
    -h|--help)
      _PRINT_HELP=1
      ;;
    --debug)
      _USE_DEBUG=1
      ;;
    -b|--base-path)
      _require_argument "${__option}" "${__maybe_param}"
      _OPTION_B_PARAM="${__maybe_param}"
       shift
      ;;
    -r|--repos)
      _require_argument "${__option}" "${__maybe_param}"
      _OPTION_R_PARAM="${__maybe_param}"
       shift
      ;;
    --endopts)
      break
      ;;
    -*)
      _die printf "Unexpected option: %s\n" "${__option}"
      ;;
  esac
  shift
done

### Functions
#####################################################################

_isDirectory() {
  local _directory="${1:-}"
  if [[ ! -d "$_directory" ]]; then
    die "Directory '$_directory' does not exist."
  else
    return 0
  fi
}

_isGitRepository() {
  local _directory="${1:-}"
  local _gitDirectory="${_directory}/.git"
  if [[ -d "$_gitDirectory" ]]; then
    return 0
  else
    return 1
  fi
}

_setBasePath() {
  local _basePath="${1:-}"
  if [[ -n "$_basePath" ]]; then
    _isDirectory "${_basePath}"
    _BASE_PATH=$_basePath
  fi
  return 0
}

_setRepositories() {
  local _params="${1:-}"
  local _directories=()
  if [[ -z "$_params" ]]; then
    while read -r line; do
      if _isGitRepository "${line}"; then
        _directories+=($line)
      fi
    done < <(find "$_BASE_PATH" -maxdepth 1 -mindepth 1 -type d)
  else
    while read -r line; do
      local _basePathWithDirectory="$_BASE_PATH$line"
      _isDirectory "${_basePathWithDirectory}"
      if ! _isGitRepository "${_basePathWithDirectory}"; then
        die "Directory '$_basePathWithDirectory' is not a git repository."
      fi
      _directories+=($_basePathWithDirectory)
    done < <(echo -e "${_params// /\\n}")
  fi
  _REPOSITORIES+=(${_directories[@]})
  return 0
}

### Runtime
#####################################################################

_main() {
  if ((_PRINT_HELP)); then
    _print_help
  else
    # Set base path
    _setBasePath "${_OPTION_B_PARAM:-}"

    # Set repositories
    _setRepositories "${_OPTION_R_PARAM:-}"

    # Exit
    exit 0
  fi
}

_main "${@:-}" # Call `_main` after everything has been defined
